import React from "react";
import {Text, Box, Flex, Button, Stack} from "@chakra-ui/react";
import type {NextPage} from "next";
import Head from "next/head";
import {AiOutlineUsergroupAdd} from "react-icons/ai";

import Header from "../components/Header";
import Footer from "../../components/Footer";

const Home: NextPage = () => {
  return (
    <Flex direction="column" minH="100vh">
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <Box as="main" flex={1} p={5} pb={0}>
        <Stack>
          <Text fontWeight={500}>
            {"In general, you owe "}
            <Text as="span" color="green.400">
              $45.25
            </Text>
          </Text>
          <Button colorScheme="purple" leftIcon={<AiOutlineUsergroupAdd />} variant="outline">
            Create new group
          </Button>
        </Stack>
      </Box>
      <Footer />
    </Flex>
  );
};

export default Home;
