import React, {useContext} from "react";
import {Text, Stack, Heading} from "@chakra-ui/react";
import type {NextPage} from "next";
import Head from "next/head";

import Layout from "@components/Layout";
import {ExpensesContext} from "@contexts";

const Home: NextPage = () => {
  const {expenses} = useContext(ExpensesContext);

  return (
    <>
      <Head>
        <title>JustPayys - Activity</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Layout>
        <Stack>
          <Text fontWeight={500}>
            {"In general, you owe "}
            <Text as="span" color="green.400">
              $45.25
            </Text>
          </Text>
          {expenses.map((expense) => (
            <Stack key={expense.id}>
              <Heading>{expense.description}</Heading>
              <Text>Total cost: {expense.cost}</Text>
            </Stack>
          ))}
        </Stack>
      </Layout>
    </>
  );
};

export default Home;
