import React from "react";
import {Text, Button, Stack} from "@chakra-ui/react";
import type {NextPage} from "next";
import Head from "next/head";
import {AiOutlineUsergroupAdd} from "react-icons/ai";

import Layout from "@components/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>JustPayys - Activity</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Layout>
        <Stack>
          <Text fontWeight={500}>
            {"In general, you owe "}
            <Text as="span" color="green.400">
              $45.25
            </Text>
          </Text>
          <Button leftIcon={<AiOutlineUsergroupAdd />} variant="outline">
            Create new group
          </Button>
        </Stack>
      </Layout>
    </>
  );
};

export default Home;
